// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.update.auto", false);
user_pref("app.update.auto.migrated", true);
user_pref("app.update.checkInstallTime", false);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.service.enabled", false);
user_pref("app.update.staging.enabled", false);
user_pref("browser.search.openintab", true);
user_pref("browser.tabs.loadBookmarksInTabs", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.bookmarks.showMobileBookmarks", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.customizemode.tip0.shown", false);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.feeds.showFirstRunUI", false);
user_pref("browser.laterrun.enabled", false);
user_pref("browser.launcherProcess.enabled", false);
user_pref("browser.newtabpage.activity-stream.feeds.section.highlights", false);
user_pref("browser.newtabpage.activity-stream.feeds.snippets", false);
user_pref("browser.newtabpage.activity-stream.prerender", false);
user_pref("browser.newtabpage.activity-stream.section.highlights.includeBookmarks", false);
user_pref("browser.newtabpage.activity-stream.section.highlights.includeDownloads", false);
user_pref("browser.newtabpage.activity-stream.section.highlights.includePocket", false);
user_pref("browser.newtabpage.activity-stream.section.highlights.includeVisited", false);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.pinned", "[{\"url\":\"http://bilibili.com/\",\"title\":\"bilibili\",\"baseDomain\":\"bilibili.com\"},{\"url\":\"http://youku.com\",\"title\":\"Youku\",\"baseDomain\":\"youku.com\"},{\"url\":\"http://www.iqiyi.com\",\"title\":\"IQiYi\",\"baseDomain\":\"iqiyi.com\"},{\"url\":\"http://v.qq.com\",\"title\":\"Tencent\",\"baseDomain\":\"v.qq.com\"},{\"url\":\"http://kyfw.12306.cn/otn\",\"title\":\"12306\",\"baseDomain\":\"kyfw.12306.cn\"},{\"url\":\"http://taobao.com\",\"title\":\"Taobao\",\"baseDomain\":\"taobao.com\"},{\"url\":\"http://share.dmhy.org/cms/page/name/programme.html\",\"title\":\"DMHY\",\"baseDomain\":\"share.dmhy.org\"},{\"url\":\"https://bbs.nga.cn/thread.php?fid=-7&order_by=postdatedesc\",\"title\":\"nga\",\"baseDomain\":\"bbs.nga.cn\"}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"shareURL\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.preferences.defaultPerformanceSettings.enabled", false);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.update", false);
user_pref("browser.search.widget.inNavBar", true);
user_pref("browser.sessionstore.max_resumed_crashes", 0);
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);;
user_pref("browser.startup.homepage", "about:newtab");
user_pref("browser.syncPromoViewsLeftMap", "{\"addons\":2,\"passwords\":3}");
user_pref("browser.tabs.crashReporting.sendReport", false);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[\"ce_easyscreenshot\",\"abp-toolbarbutton\",\"useragentoverrider-button\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"urlbar-container\",\"search-container\",\"loop-button\",\"savedpasswordeditor-button\",\"sowatchmk2-button\",\"easyscreenshot_mozillaonline_com-browser-action\",\"ublock0-button\",\"_e4a8a97b-f2ed-450b-b12d-ee082ba24781_-browser-action\",\"jid1-93wyvpgvxzgatw_jetpack-browser-action\",\"_75afe46a-7a50-4c6b-b866-c43a1075b071_-browser-action\",\"_861a3982-bb3b-49c6-bc17-4f50de104da1_-browser-action\",\"_b8ad88f9-9e0a-4e53-bbeb-aba448290381_-browser-action\",\"simple-translate_sienori-browser-action\",\"downloads-button\",\"home-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\",\"personal-bookmarks\"],\"PersonalToolbar\":[]},\"seen\":[\"abp-toolbarbutton\",\"ce_easyscreenshot\",\"action-button--acgotaku311gmailcom-baidu-link\",\"action-button--acgotaku311outlookcom-pan115-link\",\"sowatchmk2-button\",\"pocket-button\",\"developer-button\",\"easyscreenshot_mozillaonline_com-browser-action\",\"ublock0-button\",\"_e4a8a97b-f2ed-450b-b12d-ee082ba24781_-browser-action\",\"jid1-93wyvpgvxzgatw_jetpack-browser-action\",\"_75afe46a-7a50-4c6b-b866-c43a1075b071_-browser-action\",\"_861a3982-bb3b-49c6-bc17-4f50de104da1_-browser-action\",\"_b8ad88f9-9e0a-4e53-bbeb-aba448290381_-browser-action\",\"simple-translate_sienori-browser-action\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\",\"widget-overflow-fixed-list\"],\"currentVersion\":16,\"newElementCount\":7}");
user_pref("browser.uidensity", 1);
user_pref("browser.urlbar.placeholderName", "Bing");
user_pref("datareporting.healthreport.logging.consoleEnabled", false);
user_pref("datareporting.healthreport.service.enabled", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("devtools.selfxss.count", 5);
user_pref("distribution.iniFile.exists.value", false);
user_pref("extensions.langpacks.signatures.required", false);
user_pref("extensions.blocklist.enabled", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pocket.enabled", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.update.autoUpdateDefault", false);
user_pref("extensions.update.enabled", false);
user_pref("extensions.useragentoverrider.firstRun", false);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"785fb11a-44f0-41d1-b4b2-f53ad97fc1d2\",\"fxmonitor@mozilla.org\":\"12130c83-2cc6-4064-8393-a4e8bd2a5aba\",\"screenshots@mozilla.org\":\"de78c2c4-7b05-48f9-b075-9e20234f63c7\",\"webcompat-reporter@mozilla.org\":\"f44146a7-b3d1-45d8-9de4-604be2972198\",\"webcompat@mozilla.org\":\"5848ab59-bb07-4281-8add-0a7922be5e46\",\"baidu@search.mozilla.org\":\"bd5b4767-b570-42fd-b1f7-88048a62e269\",\"google@search.mozilla.org\":\"edb137ac-25d9-441e-b6d7-efc902764717\",\"bing@search.mozilla.org\":\"f491c5ae-e86f-4440-8838-b85895ebf91e\",\"ddg@search.mozilla.org\":\"2dadff38-5f9d-46b2-95b6-c2869fa1b110\",\"wikipedia@search.mozilla.org\":\"fd6542df-a9b1-405c-8567-bb01db0ac8fe\",\"amazondotcn@search.mozilla.org\":\"2be72fca-1142-4d03-b5f0-16ffbef85b6b\",\"firefox-compact-dark@mozilla.org\":\"6b558234-d903-48b6-b512-91c611e26fd7\"}");
user_pref("gfx.direct2d.disabled", true);
user_pref("layers.acceleration.disabled", true);
user_pref("layers.mlgpu.sanity-test-failed", false);
user_pref("layout.spellcheckDefault", 0);
user_pref("media.peerconnection.enabled", false);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.default.state", 2);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("pref.general.disable_button.default_browser", false);
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.advanced-layers", true);
user_pref("sanity-test.running", false);
user_pref("services.sync.declinedEngines", "prefs,tabs,addons,history");
user_pref("services.sync.deletePwdFxA", true);
user_pref("services.sync.engine.addons", false);
user_pref("services.sync.engine.history", false);
user_pref("services.sync.engine.prefs", false);
user_pref("services.sync.engine.prefs.modified", false);
user_pref("services.sync.engine.tabs", false);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("xpinstall.signatures.required", false);
user_pref("full-screen-api.macos-native-full-screen", true);
user_pref("gfx.webrender.all", true);
user_pref("gfx.webrender.software", false);
user_pref("accessibility.typeaheadfind.matchesCountLimit", 99999999);

